name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules to speed up subsequent builds
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm ci --legacy-peer-deps

      # Enforce Conventional Commits
      - name: Check Conventional Commits
        uses: amannn/action-semantic-pull-request@v3
        with:
          types: |
            fix
            feat
            chore
            docs
            refactor
            style
            test
            build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Lint the code
      - name: Run Linter
        run: npx nx affected --target=lint --base=origin/main --head=HEAD

      # Run unit tests and generate coverage report
      - name: Run Unit Tests
        run: npx nx affected --target=test --base=origin/main --head=HEAD --code-coverage
        env:
          CI: true

      # Enforce a minimum coverage threshold
      - name: Enforce Code Coverage Threshold
        run: npx nyc check-coverage --statements 90 --branches 90 --functions 90 --lines 90
        env:
          CI: true

      # Run build to ensure the project builds correctly
      - name: Build the Project
        run: npx nx affected --target=build --base=origin/main --head=HEAD

      # Run e2e tests
      - name: Run E2E Tests
        run: npx nx affected --target=e2e --base=origin/main --head=HEAD

      # Nx Cloud task distribution
      - name: Nx Cloud Task Distribution
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
        if: success()
